name: lazy_data_table
description: A Flutter data table with (optional) sticky row and/or column headers that loads the contents lazily.
version: 0.3.1
homepage: https://gitlab.com/_Naomi/lazy_data_table

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
